sudo: false
language: php

php:
- 7.0
- 7.1
- 7.2
- nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

stages:
- check
- test
- coverage

jobs:
  include:
  - stage: check
    php: 7.2
    script:
    - composer cs-check
  - stage: test
  - stage: coverage
    if: branch = master AND type = push
    php: 7.2
    env: TEST_COVERAGE=true
    script:
    after_script:
    - travis_retry composer require $COMPOSER_ARGS --dev satooshi/php-coveralls ;
    - composer test-coverage
    - travis_retry composer upload-coverage

before_install:
- travis_retry composer self-update
- if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
- travis_retry composer update

script:
- composer test
